### ISSUE TITLE
Zero-length variable name error

### ISSUE THREAD

**Issue by Aimonius** [Ryo-N7/soccer_ggplots#1]
Hi @Ryo-N7. When I try to recreate liverpool_age_utility.rmd I got this message and no plot is show: 
`"Error: attempt to use zero-length variable name"`
Any idea on where is the problem? Thanks!

**Comment by Aimonius** [comment]
Sorry I got a solution for this error, but found another one:
```
Error in theme_text(size = base_size, vjust = 1) : could not found function "theme_text"
3. mget(args, envir = env)
2. find_args(..., complete = NULL, validate = NULL)
1. theme(text = element_text(family = "Georgia"), axis.line = theme_blank(), axis.text.x = theme_text(size = base_size * 0.8, lineheight = 0.9, vjust = 1), axis.text.y = theme_text(size = base_size * 0.8, lineheight = 0.9, hjust = 1), axis.ticks = theme_segment(colour = "black", ...

```

**Comment by Aimonius** [comment]
The solution for theme_text is change to element_text, but then `Error in structure(list(family = family, face = face, colour = colour,  : 
  object 'base_size' not found`

**Comment by Ryo-N7** [comment]
hey Jesus,

use the code in the gist: https://gist.github.com/Ryo-N7/5309ba2496b4f75a0747166bfbc52270

instead of the .RMD

I think you were trying to run the LFC custom theme I was trying to create but didn't even end up using in the final plot.

**Comment by Aimonius** [comment]
Fine now with the gist code.  Thanks a lot Ryo, great job.

**Comment by Ryo-N7** [comment]
cool cool, just make sure to check the readme for the best/latest code

a lot of my RMDs are still filled with notes and unfinished stuff
